# Appium Server Configuration
appium.server.url=http://127.0.0.1:4723

# Application Details
app.package=com.credobusiness
app.activity=com.credobusiness.MainActivity

# Device/Platform Configuration
platform.name=Android
automation.name=UiAutomator2
device.name=emulator-5554
no.reset=false

# Timeouts
default.wait.seconds=10